
version: 2

models:

  - name: dim_customer_100
    description: "Customer dimension with city and state"
    columns:
      - name: customer_id
        description: "Primary key - unique identifier for customer"
        tests: [unique, not_null]
      - name: customer_unique_id
        description: "Anonymized customer ID"
      - name: customer_city
        description: "City of the customer"
      - name: customer_state
        description: "State of the customer"
      - name: customer_zip_code_prefix
        description: "ZIP code prefix of the customer"
        tests:
          - not_null
  
