version: 2

models:
  - name: dim_customers
    description: "Customer dimension with city and state"
    columns:
      - name: customer_id
        description: "Primary key"
        tests: [unique, not_null]
      - name: customer_unique_id
        description: "Unique identifier for the customer"
      - name: customer_city
        description: "City of the customer"
      - name: customer_state
        description: "State of the customer"

  - name: dim_date
    description: "Date dimension extracted from order timestamps"
    columns:
      - name: date_id
        description: "Primary key - date"
        tests: [unique, not_null]
      - name: year
        description: "Year"
      - name: month
        description: "Month"
      - name: day
        description: "Day"
      - name: day_name
        description: "Day name"
      - name: month_name
        description: "Month name"

  - name: dim_geolocation
    description: "Geographic dimension by zip code"
    columns:
      - name: geolocation_zip_code_prefix
        description: "Primary key"
        tests: [not_null]
      - name: geolocation_lat
        description: "Latitude"
      - name: geolocation_lng
        description: "Longitude"
      - name: geolocation_city
        description: "City"
      - name: geolocation_state
        description: "State"

  - name: dim_order_reviews
    description: "Customer reviews for orders"
    columns:
      - name: order_id_review_id
        description: "Composite primary key"
        tests: [unique, not_null]
      - name: review_id
        description: "Review ID"
        tests: [not_null]
      - name: order_id
        description: "Order ID"
        tests: [not_null]
      - name: review_score
        description: "Score from 1 to 5"
      - name: review_comment_title
        description: "Short title"
      - name: review_comment_message
        description: "Full comment"
      - name: review_creation_date
        description: "Date of creation"
      - name: review_answer_timestamp
        description: "Seller response timestamp"

  - name: dim_payments
    description: "Payments dimension table"
    columns:
      - name: order_id
        description: "Order ID"
        tests: [not_null]
      - name: payment_type
        description: "Type of payment"
        tests: [not_null]
      - name: payment_installments
        description: "Number of installments"

  - name: dim_products
    description: "Product dimension with category name"
    columns:
      - name: product_id
        description: "Primary key"
        tests: [unique, not_null]
      - name: product_category_name
        description: "Product category"

  - name: dim_sellers
    description: "Seller dimension with city and state"
    columns:
      - name: seller_id
        description: "Primary key"
        tests: [unique, not_null]
      - name: seller_city
        description: "City of the seller"
      - name: seller_state
        description: "State of the seller"

  - name: dim_time
    description: "Time dimension extracted from various order timestamps"
    columns:
      - name: time_id
        description: "Primary key - timestamp"
        tests: [unique, not_null]
      - name: hour
        description: "Hour extracted from timestamp"
      - name: minute
        description: "Minute extracted from timestamp"
      - name: time_hhmm
        description: "Formatted time string (HH:MM)"

  - name: fact_sales_corrected
    description: "Fact table containing individual sales transactions"
    columns:
      - name: order_id
        description: "Unique ID for the order"
        tests: [not_null]
      - name: order_item_id
        description: "Item-level granularity"
        tests: [not_null]
      - name: customer_id
        description: "Foreign key to dim_customers"
        tests: [not_null]
      - name: product_id
        description: "Foreign key to dim_products"
        tests: [not_null]
      - name: seller_id
        description: "Foreign key to dim_sellers"
        tests: [not_null]
      - name: order_status
        description: "Current order status"
      - name: order_purchase_timestamp
        description: "Datetime the order was placed"
      - name: order_approved_at
        description: "Datetime the order was approved"
      - name: order_delivered_carrier_date
        description: "Datetime order shipped"
      - name: order_delivered_customer_date
        description: "Datetime order delivered"
      - name: order_estimated_delivery_date
        description: "Datetime order was expected"
      - name: price
        description: "Price of the item"
      - name: freight_value
        description: "Freight cost for the order"
      - name: payment_type
        description: "Type of payment method used"
      - name: payment_value
        description: "Total payment value"
      - name: review_score
        description: "Customer review score"
