sources:
  - name: BET_Team3
    database: brazilian-e-commerce-team-3
    schema: BET_Team3
    tables:
      - name: customers
      - name: sellers
      - name: products_corrected
      - name: order_items_corrected
      - name: orders_corrected
      - name: order_payments
      - name: geolocation_version1
      - name: order_reviews  
