brazilian_ecommerce_team_3:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: brazilian-e-commerce-team-3
      dataset: BET_Team3
      threads: 1
      location: US
      keyfile: /home/yogan/Brazilian-E-Commerce-Team-3/brazilian_ecommerce_team_3/keys/brazilian-e-commerce-team-3-f5654e7ebd43.json
      
